/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_service_fm_FmReceiver */

#ifndef _Included_com_service_fm_FmReceiver
#define _Included_com_service_fm_FmReceiver
#ifdef __cplusplus
extern "C" {
#endif
#undef com_service_fm_FmReceiver_DEFAULT_BROADCAST_RECEIVER_PRIORITY
#define com_service_fm_FmReceiver_DEFAULT_BROADCAST_RECEIVER_PRIORITY 200L
#undef com_service_fm_FmReceiver_FUNC_REGION_NA
#define com_service_fm_FmReceiver_FUNC_REGION_NA 0L
#undef com_service_fm_FmReceiver_FUNC_REGION_EUR
#define com_service_fm_FmReceiver_FUNC_REGION_EUR 1L
#undef com_service_fm_FmReceiver_FUNC_REGION_JP
#define com_service_fm_FmReceiver_FUNC_REGION_JP 2L
#undef com_service_fm_FmReceiver_FUNC_RDS
#define com_service_fm_FmReceiver_FUNC_RDS 16L
#undef com_service_fm_FmReceiver_FUNC_RBDS
#define com_service_fm_FmReceiver_FUNC_RBDS 32L
#undef com_service_fm_FmReceiver_FUNC_AF
#define com_service_fm_FmReceiver_FUNC_AF 64L
#undef com_service_fm_FmReceiver_AUDIO_MODE_AUTO
#define com_service_fm_FmReceiver_AUDIO_MODE_AUTO 0L
#undef com_service_fm_FmReceiver_AUDIO_MODE_STEREO
#define com_service_fm_FmReceiver_AUDIO_MODE_STEREO 1L
#undef com_service_fm_FmReceiver_AUDIO_MODE_MONO
#define com_service_fm_FmReceiver_AUDIO_MODE_MONO 2L
#undef com_service_fm_FmReceiver_AUDIO_MODE_BLEND
#define com_service_fm_FmReceiver_AUDIO_MODE_BLEND 3L
#undef com_service_fm_FmReceiver_AUDIO_MODE_SWITCH
#define com_service_fm_FmReceiver_AUDIO_MODE_SWITCH 3L
#undef com_service_fm_FmReceiver_AUDIO_PATH_NONE
#define com_service_fm_FmReceiver_AUDIO_PATH_NONE 0L
#undef com_service_fm_FmReceiver_AUDIO_PATH_SPEAKER
#define com_service_fm_FmReceiver_AUDIO_PATH_SPEAKER 1L
#undef com_service_fm_FmReceiver_AUDIO_PATH_WIRE_HEADSET
#define com_service_fm_FmReceiver_AUDIO_PATH_WIRE_HEADSET 2L
#undef com_service_fm_FmReceiver_AUDIO_PATH_DIGITAL
#define com_service_fm_FmReceiver_AUDIO_PATH_DIGITAL 3L
#undef com_service_fm_FmReceiver_AUDIO_QUALITY_STEREO
#define com_service_fm_FmReceiver_AUDIO_QUALITY_STEREO 1L
#undef com_service_fm_FmReceiver_AUDIO_QUALITY_MONO
#define com_service_fm_FmReceiver_AUDIO_QUALITY_MONO 2L
#undef com_service_fm_FmReceiver_AUDIO_QUALITY_BLEND
#define com_service_fm_FmReceiver_AUDIO_QUALITY_BLEND 4L
#undef com_service_fm_FmReceiver_SCAN_MODE_NORMAL
#define com_service_fm_FmReceiver_SCAN_MODE_NORMAL 0L
#undef com_service_fm_FmReceiver_SCAN_MODE_DOWN
#define com_service_fm_FmReceiver_SCAN_MODE_DOWN 0L
#undef com_service_fm_FmReceiver_SCAN_MODE_UP
#define com_service_fm_FmReceiver_SCAN_MODE_UP 129L
#undef com_service_fm_FmReceiver_SCAN_MODE_FULL
#define com_service_fm_FmReceiver_SCAN_MODE_FULL 130L
#undef com_service_fm_FmReceiver_DEEMPHASIS_50U
#define com_service_fm_FmReceiver_DEEMPHASIS_50U 0L
#undef com_service_fm_FmReceiver_DEEMPHASIS_75U
#define com_service_fm_FmReceiver_DEEMPHASIS_75U 64L
#undef com_service_fm_FmReceiver_FREQ_STEP_100KHZ
#define com_service_fm_FmReceiver_FREQ_STEP_100KHZ 0L
#undef com_service_fm_FmReceiver_FREQ_STEP_50KHZ
#define com_service_fm_FmReceiver_FREQ_STEP_50KHZ 16L
#undef com_service_fm_FmReceiver_FM_VOLUME_MAX
#define com_service_fm_FmReceiver_FM_VOLUME_MAX 255L
#undef com_service_fm_FmReceiver_NFL_LOW
#define com_service_fm_FmReceiver_NFL_LOW 0L
#undef com_service_fm_FmReceiver_NFL_MED
#define com_service_fm_FmReceiver_NFL_MED 1L
#undef com_service_fm_FmReceiver_NFL_FINE
#define com_service_fm_FmReceiver_NFL_FINE 2L
#undef com_service_fm_FmReceiver_RDS_MODE_OFF
#define com_service_fm_FmReceiver_RDS_MODE_OFF 0L
#undef com_service_fm_FmReceiver_RDS_MODE_DEFAULT_ON
#define com_service_fm_FmReceiver_RDS_MODE_DEFAULT_ON 1L
#undef com_service_fm_FmReceiver_RDS_MODE_RDS_ON
#define com_service_fm_FmReceiver_RDS_MODE_RDS_ON 2L
#undef com_service_fm_FmReceiver_RDS_MODE_RBDS_ON
#define com_service_fm_FmReceiver_RDS_MODE_RBDS_ON 3L
#undef com_service_fm_FmReceiver_RDS_COND_NONE
#define com_service_fm_FmReceiver_RDS_COND_NONE 0L
#undef com_service_fm_FmReceiver_RDS_COND_PTY
#define com_service_fm_FmReceiver_RDS_COND_PTY 1L
#undef com_service_fm_FmReceiver_RDS_COND_TP
#define com_service_fm_FmReceiver_RDS_COND_TP 2L
#undef com_service_fm_FmReceiver_RDS_FEATURE_PS
#define com_service_fm_FmReceiver_RDS_FEATURE_PS 4L
#undef com_service_fm_FmReceiver_RDS_FEATURE_PTY
#define com_service_fm_FmReceiver_RDS_FEATURE_PTY 8L
#undef com_service_fm_FmReceiver_RDS_FEATURE_TP
#define com_service_fm_FmReceiver_RDS_FEATURE_TP 16L
#undef com_service_fm_FmReceiver_RDS_FEATURE_PTYN
#define com_service_fm_FmReceiver_RDS_FEATURE_PTYN 32L
#undef com_service_fm_FmReceiver_RDS_FEATURE_RT
#define com_service_fm_FmReceiver_RDS_FEATURE_RT 64L
#undef com_service_fm_FmReceiver_AF_MODE_OFF
#define com_service_fm_FmReceiver_AF_MODE_OFF 0L
#undef com_service_fm_FmReceiver_AF_MODE_ON
#define com_service_fm_FmReceiver_AF_MODE_ON 1L
#undef com_service_fm_FmReceiver_MIN_SIGNAL_STRENGTH_DEFAULT
#define com_service_fm_FmReceiver_MIN_SIGNAL_STRENGTH_DEFAULT 105L
#undef com_service_fm_FmReceiver_FUNCTIONALITY_DEFAULT
#define com_service_fm_FmReceiver_FUNCTIONALITY_DEFAULT 0L
#undef com_service_fm_FmReceiver_FUNC_REGION_DEFAULT
#define com_service_fm_FmReceiver_FUNC_REGION_DEFAULT 0L
#undef com_service_fm_FmReceiver_FREQ_STEP_DEFAULT
#define com_service_fm_FmReceiver_FREQ_STEP_DEFAULT 0L
#undef com_service_fm_FmReceiver_LIVE_AUDIO_QUALITY_DEFAULT
#define com_service_fm_FmReceiver_LIVE_AUDIO_QUALITY_DEFAULT 0L
#undef com_service_fm_FmReceiver_NFL_DEFAULT
#define com_service_fm_FmReceiver_NFL_DEFAULT 1L
#undef com_service_fm_FmReceiver_SIGNAL_POLL_INTERVAL_DEFAULT
#define com_service_fm_FmReceiver_SIGNAL_POLL_INTERVAL_DEFAULT 100L
#undef com_service_fm_FmReceiver_DEEMPHASIS_TIME_DEFAULT
#define com_service_fm_FmReceiver_DEEMPHASIS_TIME_DEFAULT 64L
#undef com_service_fm_FmReceiver_AF_MODE_DEFAULT
#define com_service_fm_FmReceiver_AF_MODE_DEFAULT 0L
#undef com_service_fm_FmReceiver_STATUS_OK
#define com_service_fm_FmReceiver_STATUS_OK 0L
#undef com_service_fm_FmReceiver_STATUS_FAIL
#define com_service_fm_FmReceiver_STATUS_FAIL 1L
#undef com_service_fm_FmReceiver_STATUS_SERVER_FAIL
#define com_service_fm_FmReceiver_STATUS_SERVER_FAIL 2L
#undef com_service_fm_FmReceiver_STATUS_ILLEGAL_COMMAND
#define com_service_fm_FmReceiver_STATUS_ILLEGAL_COMMAND 3L
#undef com_service_fm_FmReceiver_STATUS_ILLEGAL_PARAMETERS
#define com_service_fm_FmReceiver_STATUS_ILLEGAL_PARAMETERS 4L
/*
 * Class:     com_service_fm_FmReceiver
 * Method:    turnOnRadioNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_turnOnRadioNative
  (JNIEnv *, jobject);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    turnOffRadioNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_turnOffRadioNative
  (JNIEnv *, jobject);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    tuneRadioNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_tuneRadioNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    getRadioIsOnNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_service_fm_FmReceiver_getRadioIsOnNative
  (JNIEnv *, jobject);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    muteAudioNative
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_muteAudioNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    seekStationNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_seekStationNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    seekStationAbortNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_seekStationAbortNative
  (JNIEnv *, jobject);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    setAudioPathNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_setAudioPathNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_service_fm_FmReceiver
 * Method:    setFMVolumeNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_service_fm_FmReceiver_setFMVolumeNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_service_fm_FmReceiver_EventCallbackHandler */

#ifndef _Included_com_service_fm_FmReceiver_EventCallbackHandler
#define _Included_com_service_fm_FmReceiver_EventCallbackHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef com_service_fm_FmReceiver_EventCallbackHandler_MIN_PRIORITY
#define com_service_fm_FmReceiver_EventCallbackHandler_MIN_PRIORITY 1L
#undef com_service_fm_FmReceiver_EventCallbackHandler_NORM_PRIORITY
#define com_service_fm_FmReceiver_EventCallbackHandler_NORM_PRIORITY 5L
#undef com_service_fm_FmReceiver_EventCallbackHandler_MAX_PRIORITY
#define com_service_fm_FmReceiver_EventCallbackHandler_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
